### ISSUE TITLE
Hi, thank you for repo :) 

### ISSUE THREAD

**Issue by Aparus** [alanleungcn/puppeteer-google-translate#1]
Hi! Today I have known about the puppeteer, and it was exactly for that purpose as this repo )))
After about an hour of experiments wondering how to put in loop many texts into textarea and get their translations, I have found  your project. Thank you for sharing. I hope google will not bun you too quickly. :smile:

**Comment by alanleungcn** [comment]
Thank you for appreciating my repo, wish you a wonderful learning journey!
